language: php

php:
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

mysql:
  database: cloudbooks
  username: root
  password: root
  encoding: utf8

before_install:
  #- sudo apt-get update > /dev/null

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

before_script:
  - composer install -vvv
script: phpunit
